### ISSUE TITLE
API should stop emitting new shortcode when they expires

### ISSUE THREAD

**Issue by sponnet** [swarmcity/SwarmCityAPI#94]
currently the subscriptionShortCode emits a new shortcode whenever the validity expires. It should not do that. 
Instead we should trigger a cleanup operation for that specific shortcode that does the same as the cleanup job described in #93, but for this specific shortcode when it expires. 
So keep the current timeout , but trigger a cleanup instead.

**Comment by koenedaele** [comment]
Since #93 sweeps the DB every minute it seems enough to just implement shortCode cleanup in the subscription when the client unsubscribes. The task that is being rund during the subscription should only be run on creation and never again after that. This means removing the shortcodeChanged event as well since that can no longer happen.

**Comment by BvL13** [comment]
@eduadiez are you still working on this or is it finished?
